### PR TITLE
Minor cleanup items

### PR DESCRIPTION
**Pull request by kevhender**
Just a few cleanup items here:
1. Remove `yarn.lock` (not needed for RSF 6+, using `npm` now)
2. ~~Move some `devDependencies` into `dependencies`, if those libs are directly used in the code (makes merging this upstream repo into the PS boilerplate smoother)~~
3. Remove the overridable theme `name` property from `withStyles()`'s second parameter (this was probably copy/pasted by accident)
4. Fix class name for `Category`
5. Fix theme's `contrastText` typo
6. Move theme's `spacing` into proper hierarchy

### CODE REVIEW

**Comment by kevhender** [comment]
> Technically our projects only have dev dependencies.

@markbrocato, can you clarify what you mean by this? My understanding is that node modules that are imported into your code should be in `dependencies`, so I'm not quite sure what you mean by this.

> You should hold off until we fix that issue in the CLI.

Are you saying just to revert the package.json changes for now, and that those changes can then be redone once that CLI issue is fixed?

**Comment by markbrocato** [comment]
@kevhender Modules are only dependencies if they are required by your package at runtime.  Since we're using webpack to build everything, none of those modules are used at runtime, they are only used at build time and are therefore devDependencies.   If we were using node, then all of the modules that run on the server would be dependencies, and everything required for the client would be devDependencies.

**Comment by markbrocato** [comment]
And yes, let's just revert the package.json changes for now, and redo them once the CLI is updated.

**Comment by kevhender** [comment]
@markbrocato Great explanation, thanks. I have removed the package and package-lock changes for now.

**Comment by kevhender** [comment]
@dijs @markbrocato Can I get a review/merge here? Thanks.

**Pull request merged**
